#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git symbolic-ref --short -q HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

exec >/dev/tty 2>&1

npx lint-staged
